---
version: 2

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/kitipy
    environment:
      PIPENV_VENV_IN_PROJECT: true
      CI: true # This makes pipenv less verbose
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-cache-{{ checksum "Pipfile" }}
            - v1-deps-cache
      - run:
          name: Install Python 3.8.1
          command: |
            set -o errexit -o xtrace
            rm -rf /opt/circleci/.pyenv/
            curl https://pyenv.run | bash
            pyenv install --skip-existing 3.8.1
            pyenv global 3.8.1
      - run:
          name: Install dependencies
          command: |
            # Doesn't work with --user flag
            pip install pipenv
            pipenv install --dev
      - save_cache:
          key: v1-deps-cache-{{ checksum "Pipfile" }}
          paths:
            # pip cache contains pipenv
            - ~/.cache/pip
            - ~/.cache/pyenv/versions
            # .venv/ is the directory containing all the Python dependenies installed
            # through pipenv.
            - .venv/
            - /opt/circleci/.pyenv/
      - run:
          name: Fix authorized_keys permissions
          command: sudo chmod 0600 tests/.ssh/authorized_keys
      # - run:
      #     name: Check code style
      #     command: pipenv run ./tasks.py format
      # - run:
      #     name: Lint the code
      #     command: pipenv run ./tasks.py lint
      - run:
          name: Run tests
          command: pipenv run ./tasks.py test all
      - store_test_results:
          path: .test-results/
